### ISSUE TITLE
Very nice work in medical image!

### ISSUE THREAD

**Issue by derekshiii** [sotiraslab/AgileFormer#1]
when will you release the code?

**Comment by peijieq** [comment]
@derekshiii Thank you for being interested. I have released the (tentative) code for now. Unfortunately, I have not got any time to debug this version (but I am doing it now; I'll make sure the code is ready to run in the next a few days). I am also organizing the pretrained wieghts !  Stay tuned ! Feel free to play with the code around. The installation of the environment might be a bit bumpy, let me know if you have any questions/comments.
