### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by zhangxuan-thecastle** [sotiraslab/AgileFormer#10]
Dear author, I am very excited after reading your paper and feel that you have written it very well. However, when reproducing the code, I encountered this issue.   
I use 
torch==2.1.1+cu121
pip3 install natten==0.17.1+torch210cu121 -f https://shi-labs.com/natten/wheels/

File "/root/anaconda3/envs/AF1/lib/python3.10/site-packages/natten/utils/checks.py", line 119, in check_all_args
    check_kernel_size_arg(na_dim, kernel_size),
  File "/root/anaconda3/envs/AF1/lib/python3.10/site-packages/natten/utils/checks.py", line 61, in check_kernel_size_arg
    raise ValueError(
ValueError: Invalid value for `kernel_size`; expected an integer or tuple of integers, got <class 'torch.nn.parameter.Parameter'>

**Comment by peijieq** [comment]
Thank you for being interested in our work. I think the issue is caused by natten v.0.17.1. I would recommend using the same version (i.e., v. 0.15) as I used to avoid further issues.
