### ISSUE TITLE
MLP layer

### ISSUE THREAD

**Issue by zhangxuan-thecastle** [sotiraslab/AgileFormer#13]
Dear author, may I ask if there is an MLP layer in your code? I did not find the MLP layer

**Comment by peijieq** [comment]
@zhangxuan-thecastle Thank you for being interested in our work. The MLP layer actually implemented as convolutional layers. You can find it in the "networks/block_2d.py": https://github.com/sotiraslab/AgileFormer/blob/main/networks/blocks_2d.py. Let me know if this answers your questions.
