### ISSUE TITLE
result

### ISSUE THREAD

**Issue by zhangxuan-thecastle** [sotiraslab/AgileFormer#14]
Dear author, hello. I noticed that there are five experimental results in your article. May I ask which experimental results correspond to agileFormer_tiny.yaml and agileFormer_base.yaml in the config folder?

**Comment by peijieq** [comment]
Thanks for being interested in our work. The agileFormer_tiny.yaml corresponds to the result "AgileFormer-T w/ DS" and agileFormer_tiny.yaml corresponds to the result "AgileFormer-B w/ DS".
