### ISSUE TITLE
visualization of 3d segmentation

### ISSUE THREAD

**Issue by WuWeiZero** [sotiraslab/AgileFormer#16]
Thank you very much for your excellent work, I would like to ask about the visualization of 3d segmentation through what software, I have been working on the same work recently, using 3d slicer software can not seem to achieve the same effect

**Comment by peijieq** [comment]
Thanks for being interested. We used [3D slicer](https://www.slicer.org) for visualizing the 3D segmentation. You can simply follow [this guidance](https://slicer.readthedocs.io/en/latest/user_guide/image_segmentation.html) to load images and masks to 3D slicer. For our visualization, we took screenshoot from the rendered 3D visualization. There is more advanced way of utilizing 3D slicer by exporting your trained model to 3D slicer API.

**Comment by WuWeiZero** [comment]
@peijie-chiu Thank you for your reply. I will try it according to your guidance

**Comment by peijieq** [comment]
@WuWeiZero No problem ! Let me know if you need more help.
