### ISSUE TITLE
Error with Load Weight and Configuration Modification Impacting Accuracy: Base Model Training Inquiry

### ISSUE THREAD

**Issue by NieMinxin** [sotiraslab/AgileFormer#3]
Thank you so much for doing such a good job, I did get 86.1 accuracy with your base_best weights, but I used 3090 graphics (unlike your V100) and the environment was the same. I directly used your commands to train the model, but there was an error of load weight. I modified your configuration file and trained Base from the beginning, and the accuracy was only 84.7. I am not sure if there is any error in your configuration file, or could you please tell me how you trained base 85.7, thank you very much

**Comment by peijieq** [comment]
@NieMinxin Thank you for being interested in our work and reporting issues. It makes sense to achieve a lower performance training from scratch (without having a pretrained weight) on the multi-organ segmentation. I checked the config file, it should be correct. Could you be more specific about your error of loading the weight (e.g., the error log). Is it loading the pretrained weight from DAT++ ? If that's the case, I'll look into that (there might be some errors after I reorganized the code). It seems that I do not face any bugs when loading the pretrained weight from DAT++ from my side. I'll appreciate if you can provide more details on your errors; it would be very informative for me to verify things and save my time.

**Comment by Linzcarl** [comment]
Thank you so much for doing such a good job，I encountered an issue while installing the package with "RuntimeError: Couldn't load custom C++ops. Recompile C++extension with: Python setup.py build_ext -- in-place". I understand that the version of torch vision needs to be greater than 0.3 to use ops, but the torch vision version that is compatible with CUDA 12.1+PyTorch 2.2 is 0.17. Can you please provide the complete package and version? thanks

**Comment by thekingofbigdate** [comment]
Hello, I have also encountered [zl1216]（ https://github.com/zl1216 ）The question I raised is that I used pytorch=2.20 torch vision=0.17.0 torch studio=2.20 pytorch studio=12.1. May I know your version

**Comment by allsundayy** [comment]
Thank you so much for doing such a good job, I used CUDA 12.1, PyTorch 2.2.1, and NATTEN 0.15.0 to train the Base model from scratch, but the accuracy is only 0.845676.I am not sure if there is any error in your configuration file, or could you please tell me how you trained base 85.7, thank you very much.
![1717750485073](https://github.com/sotiraslab/AgileFormer/assets/63219279/24b9cc95-2940-4471-971c-d0a813fdc609)

**Comment by allsundayy** [comment]
Thank you so much for doing such a good job, I used CUDA 12.1, PyTorch 2.2.1, and NATTEN 0.15.0 to train the Base model from scratch, but the accuracy is only 0.845676.I am not sure if there is any error in your configuration file, or could you please tell me how you trained base 85.7, thank you very much.
![1717750775270](https://github.com/sotiraslab/AgileFormer/assets/63219279/d674a2b4-9206-4c4c-af2e-b2393b517e92)

**Comment by zhangxuan-thecastle** [comment]
> 非常感谢你们这么好的工作，我确实用你们的 base_best 权重获得了 86.1 的准确率，但我使用了 3090 图形（与你们的 V100 不同），环境是一样的。我直接使用你的命令来训练模型，但是出现了 load weight 的错误。我修改了你的配置文件，从头开始训练 Base，准确率只有 84.7。我不确定您的配置文件中是否有任何错误，或者您能否告诉我您是如何训练 base 85.7 的，非常感谢


你好，请问您在synapse上复现出85.74的结果了吗

**Comment by zhangxuan-thecastle** [comment]
> Thank you so much for doing such a good job, I did get 86.1 accuracy with your base_best weights, but I used 3090 graphics (unlike your V100) and the environment was the same. I directly used your commands to train the model, but there was an error of load weight. I modified your configuration file and trained Base from the beginning, and the accuracy was only 84.7. I am not sure if there is any error in your configuration file, or could you please tell me how you trained base 85.7, thank you very much

Hello, may I ask if you have reproduced 85.74 on the synapse dataset
