### ISSUE TITLE
An attempt was made to import the na2d_qk_with'bias function from the natten.functional file, but it did not exist.

### ISSUE THREAD

**Issue by zhangxuan-thecastle** [sotiraslab/AgileFormer#6]
Dear author, I am very excited after reading your paper and feel that you have written it very well. However, when reproducing the code, I encountered this issue. My natten and torch are both 2.20 and cu118, and there are no other issues. However, the natten.functional function does not include na2d_qk_with'bias

File "/root/data1/zhangxuanxuan/AgileFormer/networks/nat_2d.py", line 30, in <module>
    from natten.functional import na2d_av, na2d_qk_with_bias
ImportError: cannot import name 'na2d_qk_with_bias' from 'natten.functional' (/root/anaconda3/envs/AF/lib/python3.10/site-packages/natten/functional.py)

**Comment by peijieq** [comment]
@zhangxuan-thecastle Thank you for being interested in our work. I think the issue is that "na2d_qk_with_bias" has been removed in the lastest "natten". If you are using natten 2.20, then this could be an issue. My suggestion is to go back to natten 0.15.0. If this does not work, let me know. It is possible to make the code compatible with the latest natten version, but I am not sure how many efforts need to be devoted. 
 
Here is the core package versions I used:
torch==2.1.1+cu121
tvdcn==0.5.0
natten==0.15.0+torch210cu121

**Comment by zhangxuan-thecastle** [comment]
> @zhangxuan-thecastle Thank you for being interested in our work. I think the issue is that "na2d_qk_with_bias" has been removed in the lastest "natten". If you are using natten 2.20, then this could be an issue. My suggestion is to go back to natten 0.15.0. If this does not work, let me know. It is possible to make the code compatible with the latest natten version, but I am not sure how many efforts need to be devoted.
> 
> Here is the core package versions I used: torch==2.1.1+cu121 tvdcn==0.5.0 natten==0.15.0+torch210cu121


The GPU driver for the school server is 11, so I can only install cu11.6 or cu118. I used pip3 to install natten=0.14.6+torch200 cu118- f https://shi-labs.com/natten/wheels It's still not possible. This time, let's talk about it
ImportError: cannot import name 'na2d_av' from 'natten. functional' (/root/anaconda3/envs/AF/lib/python3.10/site packages/natten/functional. py), without na2d_av, is only natten=0.15.0+torch210cu121 allowed

**Comment by peijieq** [comment]
The "natten2dav, natten2dqkrpb" functions in the older version of the "natten" attention (version 0.14.6) are equivalent to "na2d_av, na2d_qk_with_bias" in the later versions. The workaround is to replace them accordingly (You can stick to your current environment given the challenges to upgrade cuda version):
```
from typing import Optional

import torch
from torch import nn, Tensor
from torch.nn.functional import pad
from torch.nn.init import trunc_normal_

from natten.functional import natten2dav, natten2dqkrpb


class NeighborhoodAttention2D(nn.Module):
    """
    Neighborhood Attention 2D Module
    """

    def __init__(
        self,
        dim: int,
        num_heads: int,
        kernel_size: int,
        dilation: int = 1,
        bias: bool = True,
        qkv_bias: bool = True,
        qk_scale: Optional[float] = None,
        attn_drop: float = 0.0,
        proj_drop: float = 0.0,
    ):
        super().__init__()
        self.num_heads = num_heads
        self.head_dim = dim // self.num_heads
        self.scale = qk_scale or self.head_dim**-0.5
        assert (
            kernel_size > 1 and kernel_size % 2 == 1
        ), f"Kernel size must be an odd number greater than 1, got {kernel_size}."
        self.kernel_size = kernel_size
        assert (
            dilation is None or dilation >= 1
        ), f"Dilation must be greater than or equal to 1, got {dilation}."
        self.dilation = dilation or 1
        self.window_size = self.kernel_size * self.dilation

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        if bias:
            self.rpb = nn.Parameter(
                torch.zeros(num_heads, (2 * kernel_size - 1), (2 * kernel_size - 1))
            )
            trunc_normal_(self.rpb, std=0.02, mean=0.0, a=-2.0, b=2.0)
        else:
            self.register_parameter("rpb", None)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x: Tensor) -> Tensor:
        if x.dim() != 4:
            raise ValueError(
                f"NeighborhoodAttention2D expected a rank-4 input tensor; got {x.dim()=}."
            )
        x = x.permute(0, 2, 3, 1)
        B, H, W, C = x.shape
        # Pad if the input is small than the minimum supported size
        H_padded, W_padded = H, W
        padding_h = padding_w = 0
        if H < self.window_size or W < self.window_size:
            padding_h = max(0, self.window_size - H_padded)
            padding_w = max(0, self.window_size - W_padded)
            x = pad(x, (0, 0, 0, padding_w, 0, padding_h))
            _, H_padded, W_padded, _ = x.shape

        qkv = (
            self.qkv(x)
            .reshape(B, H_padded, W_padded, 3, self.num_heads, self.head_dim)
            .permute(3, 0, 4, 1, 2, 5)
        )
        q, k, v = qkv[0], qkv[1], qkv[2]
        q = q * self.scale
        attn = natten2dqkrpb(q, k, self.rpb, self.kernel_size, self.dilation)
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)
        x = natten2dav(attn, v, self.kernel_size, self.dilation)
        x = x.permute(0, 2, 3, 1, 4).reshape(B, H_padded, W_padded, C)

        # Remove padding, if added any
        if padding_h or padding_w:
            x = x[:, :H, :W, :]

        return self.proj_drop(self.proj(x)).permute(0, 3, 1, 2), None, None

    def extra_repr(self) -> str:
        return (
            f"head_dim={self.head_dim}, num_heads={self.num_heads}, "
            + f"kernel_size={self.kernel_size}, dilation={self.dilation}, "
            + f"has_bias={self.rpb is not None}"
        )

if __name__ == "__main__":
    x = torch.randn(2, 16, 8, 8).cuda()
    model = NeighborhoodAttention2D(16, 8, 7).cuda()
    model(x) 
```

Let me know if this resolves the issue.

**Comment by zhangxuan-thecastle** [comment]
> The "natten2dav, natten2dqkrpb" functions in the older version of the "natten" attention (version 0.14.6) are equivalent to "na2d_av, na2d_qk_with_bias" in the later versions. The workaround is to replace them accordingly (You can stick to your current environment given the challenges to upgrade cuda version):
> 
> ```
> from typing import Optional
> 
> import torch
> from torch import nn, Tensor
> from torch.nn.functional import pad
> from torch.nn.init import trunc_normal_
> 
> from natten.functional import natten2dav, natten2dqkrpb
> 
> 
> class NeighborhoodAttention2D(nn.Module):
>     """
>     Neighborhood Attention 2D Module
>     """
> 
>     def __init__(
>         self,
>         dim: int,
>         num_heads: int,
>         kernel_size: int,
>         dilation: int = 1,
>         bias: bool = True,
>         qkv_bias: bool = True,
>         qk_scale: Optional[float] = None,
>         attn_drop: float = 0.0,
>         proj_drop: float = 0.0,
>     ):
>         super().__init__()
>         self.num_heads = num_heads
>         self.head_dim = dim // self.num_heads
>         self.scale = qk_scale or self.head_dim**-0.5
>         assert (
>             kernel_size > 1 and kernel_size % 2 == 1
>         ), f"Kernel size must be an odd number greater than 1, got {kernel_size}."
>         self.kernel_size = kernel_size
>         assert (
>             dilation is None or dilation >= 1
>         ), f"Dilation must be greater than or equal to 1, got {dilation}."
>         self.dilation = dilation or 1
>         self.window_size = self.kernel_size * self.dilation
> 
>         self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
>         if bias:
>             self.rpb = nn.Parameter(
>                 torch.zeros(num_heads, (2 * kernel_size - 1), (2 * kernel_size - 1))
>             )
>             trunc_normal_(self.rpb, std=0.02, mean=0.0, a=-2.0, b=2.0)
>         else:
>             self.register_parameter("rpb", None)
>         self.attn_drop = nn.Dropout(attn_drop)
>         self.proj = nn.Linear(dim, dim)
>         self.proj_drop = nn.Dropout(proj_drop)
> 
>     def forward(self, x: Tensor) -> Tensor:
>         if x.dim() != 4:
>             raise ValueError(
>                 f"NeighborhoodAttention2D expected a rank-4 input tensor; got {x.dim()=}."
>             )
>         x = x.permute(0, 2, 3, 1)
>         B, H, W, C = x.shape
>         # Pad if the input is small than the minimum supported size
>         H_padded, W_padded = H, W
>         padding_h = padding_w = 0
>         if H < self.window_size or W < self.window_size:
>             padding_h = max(0, self.window_size - H_padded)
>             padding_w = max(0, self.window_size - W_padded)
>             x = pad(x, (0, 0, 0, padding_w, 0, padding_h))
>             _, H_padded, W_padded, _ = x.shape
> 
>         qkv = (
>             self.qkv(x)
>             .reshape(B, H_padded, W_padded, 3, self.num_heads, self.head_dim)
>             .permute(3, 0, 4, 1, 2, 5)
>         )
>         q, k, v = qkv[0], qkv[1], qkv[2]
>         q = q * self.scale
>         attn = natten2dqkrpb(q, k, self.rpb, self.kernel_size, self.dilation)
>         attn = attn.softmax(dim=-1)
>         attn = self.attn_drop(attn)
>         x = natten2dav(attn, v, self.kernel_size, self.dilation)
>         x = x.permute(0, 2, 3, 1, 4).reshape(B, H_padded, W_padded, C)
> 
>         # Remove padding, if added any
>         if padding_h or padding_w:
>             x = x[:, :H, :W, :]
> 
>         return self.proj_drop(self.proj(x)).permute(0, 3, 1, 2), None, None
> 
>     def extra_repr(self) -> str:
>         return (
>             f"head_dim={self.head_dim}, num_heads={self.num_heads}, "
>             + f"kernel_size={self.kernel_size}, dilation={self.dilation}, "
>             + f"has_bias={self.rpb is not None}"
>         )
> 
> if __name__ == "__main__":
>     x = torch.randn(2, 16, 8, 8).cuda()
>     model = NeighborhoodAttention2D(16, 8, 7).cuda()
>     model(x) 
> ```
> 
> Let me know if this resolves the issue.


It has been resolved. Thank you to the author
